// export const REGISTER_SUCCESS = 'REGISTER_SUCCES';
// export const REGISTER_FAIL = 'REGISTER_FAIL';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAIL = 'LOGIN_FAIL';
// export const LOGOUT = 'LOGOUT';

// export const SET_MESSAGE = 'SET_MESSAGE';
// export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// export const POSTBAHANBAKU_SUCCESS = 'POSTBAHANBAKU_SUCCESS';
// export const POSTBAHANBAKU_FAIL = 'POSTBAHANBAKU_FAIL';
// export const POSTPESANONLINE_SUCCESS = 'POSTPESANONLINE_SUCCESS';
// export const POSTPESANONLINE_FAIL = 'POSTPESANONLINE_FAIL';
// export const POSTPERALATAN_SUCCESS = 'POSTPERALATAN_SUCCESS';
// export const POSTPERALATAN_FAIL = 'POSTPERALATAN_FAIL';
// export const POSTPERLENGKAPAN_SUCCESS = 'POSTPERLENGKAPAN_SUCCESS';
// export const POSTPERLENGKAPAN_FAIL = 'POSTPERLENGKAPAN_FAIL';
// export const POSTJADI_SUCCESS = 'POSTJADI_SUCCESS';
// export const POSTJADI_FAIL = 'POSTJADI_FAIL';
// export const POSTJUAL_SUCCESS = 'POSTJUAL_SUCCESS';
// export const POSTJUAL_FAIL = 'POSTJUAL_FAIL';